# Generated by Django 6.1.1 on 2026-09-24 08:26

from django.conf import settings
from django.db import migrations


def assign_owner(apps, schema_editor):
    # Modèles "historiques" : l'état du schéma à cette migration,
    # pas les classes actuelles de models.py.
    Project = apps.get_model("projects", "Project")
    User = apps.get_model(settings.AUTH_USER_MODEL)

    orphans = Project.objects.filter(owner__isnull=True)
    if not orphans.exists():
        return

    superuser = User.objects.filter(is_superuser=True).order_by("pk").first()
    if superuser is None:
        raise RuntimeError(
            "Des projets existent sans propriétaire et aucun superuser n'a été "
            "trouvé. Créez-en un avec `python manage.py createsuperuser` "
            "puis relancez `migrate`."
        )

    orphans.update(owner=superuser)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(assign_owner, migrations.RunPython.noop),
    ]
